apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
  ## namespace: develop
  labels:
    app: currency-conversion-rest
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "currency-conversion"
    tags.datadoghq.com/version: "v1.9.16"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion-rest
  template:
    metadata:
      name: currency-conversion-pod
      #annotations:
      #  ad.datadoghq.com/currency-conversion.logs: '[<LOG_CONFIG>]'      
      ## namespace: develop
      labels:
        app: currency-conversion-rest
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "currency-conversion"
        tags.datadoghq.com/version: "v1.9.16"
      #annotations:
      #  ad.datadoghq.com/currency-conversion.logs: |-
      #    [{
      #      "source": "java",
      #      "log_processing_rules": [
      #        {
      #          "type": "multi_line",
      #          "name": "log_start_with_date",
      #          "pattern": "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"
      #        }
      #      ]
      #    }]  
               
    spec:
      containers:
      - name: agent
        image: otel/opentelemetry-collector-contrib:latest # otel/opentelemetry-collector:0.18.0
        args:
        - --config=/conf/otel-agent-config.yaml
        volumeMounts:
        - mountPath: /conf
          name: otel-agent-config-vol 
      - name: currency-conversion
        #image: gcr.io/sbx-app/currency-conversion:latest
        image: hbracho/currency-conversion:v0.1.7
        ports:
        - containerPort: 8080
        env:              
          ##- name: DD_ENV
          ##  valueFrom:
          ##    fieldRef:
          ##      fieldPath: metadata.labels['tags.datadoghq.com/env']
          ##- name: DD_SERVICE
          ##  valueFrom:
          ##    fieldRef:
          ##      fieldPath: metadata.labels['tags.datadoghq.com/service']
          ##- name: DD_VERSION
          ##  valueFrom:
          ##    fieldRef:
          ##      fieldPath: metadata.labels['tags.datadoghq.com/version']        
          ##- name: DD_AGENT_HOST
          ##  valueFrom:
          ##    fieldRef:
          ##      fieldPath: status.hostIP
          ##-------start opentelemetry--------
          ##- name: HOST_IP
          ##  valueFrom:
          ##    fieldRef:
          ##      fieldPath: status.hostIP
          ##- name: OTEL_EXPORTER_OTLP_ENDPOINT
          ##  value: "http://$(HOST_IP):55680"
          ##- name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          ##  value: "http://$(HOST_IP):55680"
          ##- name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          ##  value: "http://$(HOST_IP):55680"            
          ##- name: DD_LOGS_INJECTION
          ##  value: "true"
        ##-------finish opentelemetry--------                            
        #- name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
        #  value: "true"
        #- name: DD_TRACE_ANALYTICS_ENABLED
        #  value: "true"
      volumes:
      - configMap:
          name: otel-agent-conf
          items:
            - key: otel-agent-config
              path: otel-agent-config.yaml
        name: otel-agent-config-vol           

            
---

apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
  ## namespace: develop
  labels:
    app: currency-conversion-rest
spec:
  selector:
    app: currency-conversion-rest
  ports:
     - port: 8080
  type: ClusterIP #NodePort #only apply LoadBalancer or NodePort app=api-gce